### ISSUE TITLE
1st <2023-12-01> I'm the most active Chinese member of this community.

### ISSUE THREAD

**Issue by zqxinran** [daqnext/meson-grants#6]
I'm the most active user from China in the MESON community.

At present, only these two Chinese communities are known, and relatively more users use Chinese to communicate:

1、https://t.me/mesoncn
Because the MESON community does not provide an official Chinese Telegram group. So there is such a group for Chinese users.

2、https://discord.com/channels/784251111678148608/994080840235634708
This is the Chinese communication sub-channel of MESON's official discord channel.

**Comment by bitruss** [comment]
Hey @zqxinran, could you answer the questions with format below:

### What is your idea, and how did you implement it?

### How do you develop the Meson ecosystem?

### Data Analysis

### Links and submissions
